[project]
name = "pandas-msgpack"
version = "0.1.1"
description = "Pandas interface to msgpack"
readme = "README.rst"
classifiers=[
    'Development Status :: 4 - Beta',
    'Environment :: Console',
    'Intended Audience :: Science/Research',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 2',
    'Programming Language :: Python :: 2.7',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Topic :: Scientific/Engineering',
]
license = {file = 'LICENSE.md'}

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "linux-aarch64", "win-64"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.system-requirements]
libc = "2.17"
linux = "3.10.0"

[tool.pixi.pypi-dependencies]
pandas = ">=1.0.0,<2"

[tool.pixi.environments]
build = ['build']

[tool.pixi.tasks]
build = { cmd = [
    "python", 
    "setup.py", 
    "sdist", 
    "--formats=gztar"
    ], description = "Build the package" }
test = { cmd = [
    "pytest --tb=short -q --disable-warnings"
    ], description = "Run the tests" }

[tool.pixi.feature.build.dependencies]
setuptools = "*"
cython = ">=3.0.12,<4"
