[project]
name = "isf-pandas-msgpack-test"
description = "Pandas interface to msgpack - ISF patch"
version = "0.1.21"
classifiers=[
    'Development Status :: 4 - Beta',
    'Environment :: Console',
    'Intended Audience :: Science/Research',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Topic :: Scientific/Engineering',
]
license = {file = 'LICENSE.md'}

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "linux-aarch64", "win-64"]

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "Cython"]

[tool.hatch.build.hooks.cython]
extensions = [
    {name = "pandas_msgpack._move", sources = ["pandas_msgpack/move.c"]},
    {name = "pandas_msgpack.msgpack._packer", sources = ["pandas_msgpack/msgpack/_packer.pyx"], language = "c++", include-dirs = ["pandas_msgpack/includes"], define-macros = ["__LITTLE_ENDIAN__"]},
    {name = "pandas_msgpack.msgpack._unpacker", sources = ["pandas_msgpack/msgpack/_unpacker.pyx"], language = "c++", include-dirs = ["pandas_msgpack/includes"], define-macros = ["__LITTLE_ENDIAN__"]},
]

[tool.pixi.system-requirements]
libc = "2.17"
linux = "3.10.0"

[tool.pixi.environments]
build = ['build']

[tool.pixi.tasks]
build_ext = { cmd = [
    "python", "setup.py", "build_ext", "--inplace"
    ], description = "Build the Cython extensions" }
build = { cmd = [
    "python", "setup.py", "sdist", "--formats=gztar"
    ], description = "Build the package" }
test = { cmd = [
    "pytest --tb=short -q --disable-warnings"
    ], description = "Run the tests" }

[tool.pixi.feature.build.dependencies]
setuptools = "*"
cython = ">=3.0.12,<4"
twine = ">=6.1.0,<7"
hatch = ">=1.14.0,<2"
pip = ">=25.0.1,<26"
pandas = ">=1.0.0,<2"