name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build & test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        pandas_version: [11, 12, 13, 14, 15, 20, 21, 22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pixi environments
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.46.0
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
          manifest-path: pyproject.toml

      - name: Build wheel & sdist
        run: |
          pixi r -e build-pandas-v${{ matrix.pandas_version }} build

      - name: Install wheel
        run: |
          wheel=$(realpath $(echo dist/*.whl))

          # Install in default env, since installing wheels as features is not yet supported
          # This breaks the default env
          # Last checked on pixi 0.46
          pixi add --pypi "isf_pandas_msgpack @ file://$wheel"

      - name: Run test suite
        run: pixi r -e test-pandas-v${{ matrix.pandas_version }} test
          