name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build & test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pixi environments
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.46.0
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
          manifest-path: pyproject.toml

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython setuptools setuptools-scm build

      - name: Build the package
        run: |
          python -m build --sdist --wheel
      
      - name: Install the package
        run: |
          python -c "import glob; import subprocess; subprocess.check_call(['pip', 'install', glob.glob('dist/*.whl')[0]])"

      - name: Run tests for `pandas 1.1` to `pandas 2.2`
        run: |
          pixi r -e test-pandas-v11 test
          pixi r -e test-pandas-v12 test
          pixi r -e test-pandas-v13 test
          pixi r -e test-pandas-v14 test
          pixi r -e test-pandas-v20 test
          pixi r -e test-pandas-v21 test
          pixi r -e test-pandas-v22 test