name: Test Suite

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        pandas-version: ["11", "12", "13", "14", "15", "20", "21", "22"]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: prefix-dev/setup-pixi@v0.8.3
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Build the extensions
        run: pixi r -e test-pandas-v${{ matrix.pandas-version }} build_ext

      - name: Run tests
        run: pixi r -e test-pandas-v${{ matrix.pandas-version }} test